language: rust
sudo: false

cache:
  directories:
  - "/home/travis/.cargo"

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
  - git config --local user.name "Ben Konz"
  - git config --local user.email "benkonz@protonmail.com"
  - name="gameboy_emulator-$TRAVIS_TAG-$TARGET"
  - mkdir $name
  - cp target/$TARGET/release/gameboy_emulator $name/
  - cp README.md LICENSE $name/
  - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key:
      secure: X/FBZ4eyAiGk6S4YLHaVv94QDxDpdLA3GKKDFZnzQ5HL5XVunaSUE4ZFjn2MlTBpyL8Rn7rKMjYiz9eSjN71bUdbPGsujCjaLT+tf7UKWbie5j5ouV4U2oE1o13BPNZEahZkLiQTIEQ/2lLqhoj+k0Oz207/fUMUDZNL31AbmgNgWn5C3b2Gq3QRZwSLS4TTH4SulFAW6O+H/LA3cwoMOe9SEj76RNqwrOhziWJeZor3WpYvOFHUBfuMrs438y+GMJkE0VZ2n74R9tdvJjbNe0BeY7WZO2GgQxtBeZd6OJRGZ2tf4ELNTkHp0WsYt42FaDlQLty5Ren2RC9Zg9TZXwNqJRR+5VeyaF7AA2W0QRzbSDMIl16fOIXSZUW8zjCdEbHNY0SGPKkcWDAWeNVuFTDK/PC5gCMqKmvPlqFz0DTLvMnmPtCgxYPaex3d2Wa0FXRofhirVFSwJ1rg9T4eGg8MP2XMKVE/H69W9OayIEw2ZZ+sghmiumZ5EL3D4gr6l/0Cc1kG4cK+/VcCFEB9/DmCqHDmTpGoDDNX9j2faW5MSMlOXwjA4QR3/k2lDU+jlEP8oCN5yzDp0ZyFA/lW8Hl6yzUVUyBHFblQj8hTPIRpRCnGJGwskTko4j9WRLF9RxH77HiC+dRMTjgtOzbW22L76etLezFnRT1Rlp2i3Oc=
    file: gameboy_emulator-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true
matrix:
  include:
  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-gnu
    rust: stable
    before_script: rustup target add $TARGET
    script: cargo build --package gameboy_opengl --bin gameboy_emulator --release --target $TARGET --locked
    <<: *DEPLOY_TO_GITHUB

  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: stable
    script: cargo build --release --package gameboy_opengl --bin gameboy_emulator --target $TARGET --locked
    install: true
    <<: *DEPLOY_TO_GITHUB

notifications:
  email:
    on_success: never
