language: rust
sudo: false

cache:
  directories:
  - "/home/travis/.cargo"

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
  - git config --local user.name "Ben Konz"
  - git config --local user.email "benkonz@protonmail.com"
  - name="gameboy_emulator-$TRAVIS_TAG-$TARGET"
  - mkdir $name
  - cp target/$TARGET/release/gameboy_emulator $name/
  - cp README.md LICENSE $name/
  - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key:
      secure: NYeZLevhp+ew/zP0DBAGqVz/QD6YtSgyfdjT6Tu3/1UzHnrm6YgoViUMwIgVuiZoxuejsaen6IenX0QhbhjYYFuIjfX2asSb3S+is+Eap3AfSMZbLkruu6KoVGcebEI5bnf+4knzejtXhuQgOxAemZWTYoD0Dvq2XVnb5gX/lyBLDEcanyZKJHhhn3RlfjgzT6Fj4EcBFzLGcHY1fE6WJXh6uwUh3Cj2zf3wy0KmVftnV7GzKePadmrPdm+CMfmYD0ecX/mn1+7dsDBLEhhkcyh6oBMDcl/LoImLlngVk+aWdZARkBfYP+dcrK4RUULwSrB3iS70Kt57eHZNyvwPPAfq+6YK+i45tOtDjM1+DnwhB5mncKVBKLqWcAZbga4TyG7mQxxQDNxpSf6+eqgPFf1TGTRCvnvUJG/Mm0kUIrgeJHq6p5Cuoe1o2DX9W04TW1A6B91ozh5+tD8kYoGYHA9b9kmw8+2rTK7i3U6rYaDV2AWp4ng1kw/Armfu2gsO1Sb1hPZM2/+tQEIuJU4BfLZDxzOIEYU84biMZlga9s7+NffJFRnXB57wu30BIgUurWbpl4xdYr59/Yau7dU3S0NEhIneTTNsVuAZogGV4Zc5xLT9FfgjyCUaeAOs+y5QwZUmQCoZuTNVLO33lf69Qosw+n8XsnSJOFzQHVDKnTM=
    file: gameboy_emulator-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true
matrix:
  include:
  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-gnu
    rust: stable
    before_script: rustup target add $TARGET
    script: cargo build --package gameboy_opengl --bin gameboy_emulator --release --target $TARGET --locked
    <<: *DEPLOY_TO_GITHUB

  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: stable
    script: cargo build --release --package gameboy_opengl --bin gameboy_emulator --target $TARGET --locked
    install: true
    <<: *DEPLOY_TO_GITHUB

notifications:
  email:
    on_success: never
