[package]
name = "gameboy_emulator"
version = "0.1.0"
authors = ["Ben Konz <bkonz@unomaha.edu>"]

[dependencies]
gameboy_opengl = { path = "gameboy_opengl" }

[workspace]

[lib]
name = "gameboy_lib"
crate-type = ["cdylib"]