[package]
name = "gameboy_core"
version = "0.1.9"
authors = ["Ben Konz <bkonz@unomaha.edu>"]
license = "Apache-2.0"
repository = "https://github.com/bkonzUNOmaha/gameboy_core"
description = "core library to be used for Gameboy emulation"

[dependencies]
bitflags = "1.0"