[package]
name = "gameboy_opengl"
version = "0.1.7"
authors = ["Ben Konz <benkonz@protonmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/benkonz/gameboy_emulator"
description = "opengl library for use in gameboy emulation with the gameboy_core library"

[[bin]]
name = "gameboy_emulator"

[dependencies]
gameboy_core = { path = "../gameboy_core", version = "0.2" }
glutin = "0.22.0-alpha5"
clap = "2.33"
directories = "2.0"

[build-dependencies]
gl_generator = "0.14"
