[package]
name = "gameboy_opengl"
version = "0.1.4"
authors = ["Ben Konz <bkonz@unomaha.edu>"]
license = "Apache-2.0"
repository = "https://github.com/bkonzUNOmaha/gameboy_opengl"
description = "opengl library for use in gameboy emulation with the gameboy_core library"

[[bin]]
name = "gameboy_emulator"

[dependencies]
gameboy_core = { path = "../gameboy_core" }
glutin = "0.22.0-alpha3"
c_str_macro = "1.0"

[build-dependencies]
gl_generator = "0.13"
