[package]
name = "gameboy_opengl"
version = "0.2.0"
authors = ["Ben Konz <benkonz@protonmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/benkonz/gameboy_emulator"
description = "opengl library for use in gameboy emulation with the gameboy_core library"

[[bin]]
name = "gameboy_emulator"

[dependencies]
gameboy_core = { path = "../gameboy_core", version = "0.2.6" }
clap = "2.33"
directories = "2.0"
gl = "0.14.0"

[dependencies.sdl2]
version = "0.32.2"
features = ["bundled", "static-link"]